# Generated by Django 5.2.7 on 2025-11-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                ("ID_Funcionario", models.AutoField(primary_key=True, serialize=False)),
                ("Nome", models.CharField(max_length=100)),
                ("Cargo", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100, unique=True)),
                ("Telefone", models.CharField(max_length=15, unique=True)),
                ("CPF", models.CharField(max_length=15, unique=True)),
                ("Turno", models.CharField(max_length=50)),
                ("Empresa", models.CharField(max_length=100)),
                ("Setor", models.CharField(max_length=100)),
                ("Matricula", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plataforma",
            fields=[
                ("ID_Plataforma", models.AutoField(primary_key=True, serialize=False)),
                ("Nome", models.CharField(max_length=100)),
                ("Localizacao", models.CharField(max_length=200)),
                ("Responsavel", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OcorrenciaQueima",
            fields=[
                (
                    "ID_OcorrenciaQueima",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Responsavel", models.CharField(max_length=100)),
                ("Data_Hora", models.DateTimeField()),
                ("Vazao", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Gas", models.CharField(max_length=100)),
                ("ClassificacaoQueima", models.CharField(max_length=50)),
                ("StatusComunicacao", models.CharField(max_length=20)),
                (
                    "ID_Funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operadores.funcionario",
                    ),
                ),
                (
                    "ID_Plataforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operadores.plataforma",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="funcionario",
            name="ID_Plataforma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="operadores.plataforma",
            ),
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                ("ID_Equipamento", models.AutoField(primary_key=True, serialize=False)),
                ("Nome", models.CharField(max_length=100)),
                ("Tipo", models.CharField(max_length=100)),
                ("Fabricante", models.CharField(blank=True, max_length=100, null=True)),
                ("Modelo", models.CharField(blank=True, max_length=100, null=True)),
                ("Status", models.CharField(max_length=50)),
                (
                    "ID_Plataforma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="operadores.plataforma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroEquipamento",
            fields=[
                ("ID_Registro", models.AutoField(primary_key=True, serialize=False)),
                ("Data_Hora", models.DateTimeField()),
                ("Status_Operacional", models.CharField(max_length=50)),
                (
                    "ID_Equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operadores.equipamento",
                    ),
                ),
                (
                    "ID_Funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operadores.funcionario",
                    ),
                ),
            ],
        ),
    ]
