# Generated by Django 5.2.7 on 2025-11-05 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operadores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroequipamento",
            name="ID_Equipamento",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="ID_Plataforma",
        ),
        migrations.RemoveField(
            model_name="ocorrenciaqueima",
            name="ID_Funcionario",
        ),
        migrations.RemoveField(
            model_name="registroequipamento",
            name="ID_Funcionario",
        ),
        migrations.RemoveField(
            model_name="ocorrenciaqueima",
            name="ID_Plataforma",
        ),
        migrations.DeleteModel(
            name="Equipamento",
        ),
        migrations.DeleteModel(
            name="Funcionario",
        ),
        migrations.DeleteModel(
            name="RegistroEquipamento",
        ),
        migrations.DeleteModel(
            name="OcorrenciaQueima",
        ),
        migrations.DeleteModel(
            name="Plataforma",
        ),
    ]
