# Generated by Django 5.2.8 on 2026-01-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_plataforma_equipemanutencao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="Status_Operacional",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("inativo", "Inativo"),
                    ("manutencao", "Em Manutenção"),
                ],
                max_length=20,
            ),
        ),
    ]
