# Generated by Django 5.2.8 on 2026-01-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_equipamento_status_operacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='Modelo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='Tipo',
        ),
    ]
