# Generated by Django 5.2.8 on 2026-01-07 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_remove_equipamento_modelo_remove_equipamento_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipamento",
            name="Funcionario",
        ),
    ]
