# Generated by Django 5.2.8 on 2026-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0010_alter_funcionario_turno"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="Cidade",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="Supervisor",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
