# Generated by Django 5.2.8 on 2026-01-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0013_funcionario_permissao_alter_funcionario_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="Permissao",
            field=models.CharField(
                choices=[
                    ("operador", "Operador"),
                    ("gerente", "Gerente"),
                    ("administrador", "Administrador"),
                ],
                max_length=100,
            ),
        ),
    ]
