# Generated by Django 5.2.8 on 2026-01-10 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0014_alter_funcionario_permissao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="Empresa",
        ),
    ]
