# Generated by Django 5.2.10 on 2026-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_rename_fabricante_equipamento_fabricante_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['status_operacional'], name='database_eq_status__5bc36a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['codigo'], name='database_eq_codigo_226bef_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['cpf'], name='database_fu_cpf_c6c0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['setor'], name='database_fu_setor_757d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciaqueima',
            index=models.Index(fields=['plataforma', 'data_hora'], name='database_oc_platafo_9107c2_idx'),
        ),
        migrations.AddIndex(
            model_name='plataforma',
            index=models.Index(fields=['status', 'tipo'], name='database_pl_status_59bd9a_idx'),
        ),
    ]
