# Generated by Django 5.2.7 on 2025-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialQueimado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('massa_kg', models.FloatField(verbose_name='Massa (kg)')),
                ('temperatura_c', models.FloatField(verbose_name='Temperatura de Queima (°C)')),
                ('duracao_s', models.FloatField(verbose_name='Duração (segundos)')),
                ('data_queima', models.DateTimeField(verbose_name='Data/Hora da Queima')),
            ],
        ),
    ]
