# Generated by Django 5.2.7 on 2025-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DadosQueima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialqueimado',
            name='eficiencia',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialqueimado',
            name='tipo_queima',
            field=models.CharField(default='Rotineira', max_length=50),
        ),
        migrations.AddField(
            model_name='materialqueimado',
            name='volume_gas',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
