# Generated by Django 5.2.7 on 2025-11-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DadosQueima', '0003_resumoqueima'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumoQueima',
            new_name='QueimaDTO',
        ),
    ]
