# Generated by Django 5.2.8 on 2025-11-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DadosQueima', '0004_rename_resumoqueima_queimadto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueimaDTO',
        ),
        migrations.AddField(
            model_name='materialqueimado',
            name='nome_gas',
            field=models.CharField(default='Gás A', max_length=100),
        ),
    ]
