# Generated by Django 5.2.8 on 2026-01-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DadosQueima', '0005_delete_queimadto_materialqueimado_nome_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialqueimado',
            name='data_queima',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
