# Generated by Django 6.0.2 on 2026-02-27 17:20

import DadosQueima.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DadosQueima", "0006_alter_materialqueimado_data_queima"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialqueimado",
            name="plataforma",
            field=models.CharField(
                default=DadosQueima.models.plataforma_aleatoria, max_length=100
            ),
        ),
    ]
